//! `new` — scaffolding a spec, a workflow or a skill.
//!
//! Split out of `dispatch/catalogue.rs` by WI 0114 F-51. The specs are data;
//! `ROOT` in `mod.rs` is what assembles them into the tree.

use super::*;

// ── new ─────────────────────────────────────────────────────────────────────

pub(super) const NEW: CommandSpec = CommandSpec {
    name: "new",
    aliases: &[],
    help: "Create a new awman artefact (spec, workflow, or skill).",
    long_help: None,
    arguments: &[],
    flags: &[],
    api_allowed: false,
    build: crate::command::dispatch::build::unsupported,
    gateway_need: GatewayNeed::None,
    requires_container_tier: false,
    requires_runtime: true,
    opens_tui_when_bare: false,
    subcommands: &[&NEW_SPEC, &NEW_WORKFLOW, &NEW_SKILL],
};

pub(super) const NEW_SPEC: CommandSpec = CommandSpec {
    name: "spec",
    aliases: &[],
    help: "Create a new work item spec.",
    long_help: None,
    arguments: &[],
    flags: &[
        FlagSpec {
            long: "interview",
            short: None,
            help: "Use interview mode.",
            kind: FlagKind::Bool,
            default: FlagDefault::Bool(false),
            frontends: FrontendVisibility::All,
            conflicts_with: &[],
            implies: &[],
            optional: true,
        },
        FlagSpec {
            long: "non-interactive",
            short: Some('n'),
            help: "Run the interview agent in non-interactive (print) mode.",
            kind: FlagKind::Bool,
            default: FlagDefault::Bool(false),
            frontends: FrontendVisibility::All,
            conflicts_with: &[],
            implies: &[],
            optional: true,
        },
        FlagSpec {
            long: "issue",
            short: None,
            help: "GitHub issue number, URL, or owner/repo#N to use as spec input.",
            kind: FlagKind::OptionalString,
            default: FlagDefault::None,
            frontends: FrontendVisibility::All,
            conflicts_with: &[],
            implies: &[],
            optional: true,
        },
    ],
    api_allowed: false,
    build: crate::command::dispatch::build::new,
    gateway_need: GatewayNeed::None,
    requires_container_tier: false,
    requires_runtime: true,
    opens_tui_when_bare: false,
    subcommands: &[],
};

pub(super) const WORKFLOW_FORMAT_VALUES: &[&str] = &["toml", "yaml"];

pub(super) const NEW_WORKFLOW: CommandSpec = CommandSpec {
    name: "workflow",
    aliases: &[],
    help: "Interactively create a new workflow file.",
    long_help: None,
    arguments: &[],
    flags: &[
        FlagSpec {
            long: "interview",
            short: None,
            help: "Let a code agent complete the workflow from a summary you provide.",
            kind: FlagKind::Bool,
            default: FlagDefault::Bool(false),
            frontends: FrontendVisibility::All,
            conflicts_with: &[],
            implies: &[],
            optional: true,
        },
        FlagSpec {
            long: "non-interactive",
            short: Some('n'),
            help: "Run the interview agent in non-interactive (print) mode.",
            kind: FlagKind::Bool,
            default: FlagDefault::Bool(false),
            frontends: FrontendVisibility::All,
            conflicts_with: &[],
            implies: &[],
            optional: true,
        },
        FlagSpec {
            long: "global",
            short: None,
            help: "Write to ~/.awman/workflows/<name> instead of the current repo.",
            kind: FlagKind::Bool,
            default: FlagDefault::Bool(false),
            frontends: FrontendVisibility::All,
            conflicts_with: &[],
            implies: &[],
            optional: true,
        },
        FlagSpec {
            long: "format",
            short: None,
            help: "Output file format.",
            kind: FlagKind::Enum(WORKFLOW_FORMAT_VALUES),
            default: FlagDefault::Str("toml"),
            frontends: FrontendVisibility::All,
            conflicts_with: &[],
            implies: &[],
            optional: true,
        },
    ],
    api_allowed: false,
    build: crate::command::dispatch::build::new,
    gateway_need: GatewayNeed::None,
    requires_container_tier: false,
    requires_runtime: true,
    opens_tui_when_bare: false,
    subcommands: &[],
};

pub(super) const NEW_SKILL: CommandSpec = CommandSpec {
    name: "skill",
    aliases: &[],
    help: "Interactively create a new skill file.",
    long_help: None,
    arguments: &[],
    flags: &[
        FlagSpec {
            long: "interview",
            short: None,
            help: "Let a code agent complete the skill body from a summary you provide.",
            kind: FlagKind::Bool,
            default: FlagDefault::Bool(false),
            frontends: FrontendVisibility::All,
            conflicts_with: &[],
            implies: &[],
            optional: true,
        },
        FlagSpec {
            long: "non-interactive",
            short: Some('n'),
            help: "Run the interview agent in non-interactive (print) mode.",
            kind: FlagKind::Bool,
            default: FlagDefault::Bool(false),
            frontends: FrontendVisibility::All,
            conflicts_with: &[],
            implies: &[],
            optional: true,
        },
        FlagSpec {
            long: "global",
            short: None,
            help: "Write to ~/.awman/skills/<name>/ instead of the current repo.",
            kind: FlagKind::Bool,
            default: FlagDefault::Bool(false),
            frontends: FrontendVisibility::All,
            conflicts_with: &[],
            implies: &[],
            optional: true,
        },
        FlagSpec {
            long: "pull",
            short: None,
            help: "Pull (or refresh) a published skills library from GitHub, e.g. github.com/obra/superpowers.",
            kind: FlagKind::OptionalString,
            default: FlagDefault::None,
            frontends: FrontendVisibility::All,
            conflicts_with: &["pull-all", "interview", "global"],
            implies: &[],
            optional: true,
        },
        FlagSpec {
            long: "pull-all",
            short: None,
            help: "Refresh every previously-pulled skills library.",
            kind: FlagKind::Bool,
            default: FlagDefault::Bool(false),
            frontends: FrontendVisibility::All,
            conflicts_with: &["pull", "subdir", "interview", "global"],
            implies: &[],
            optional: true,
        },
        FlagSpec {
            long: "subdir",
            short: None,
            help: "Subdirectory inside the pulled repo containing skills (default: skills).",
            kind: FlagKind::OptionalString,
            default: FlagDefault::None,
            frontends: FrontendVisibility::All,
            conflicts_with: &["pull-all"],
            implies: &[],
            optional: true,
        },
    ],
    api_allowed: false,
     build: crate::command::dispatch::build::new,
    gateway_need: GatewayNeed::None,
    requires_container_tier: false,
    requires_runtime: true,
    opens_tui_when_bare: false,
    subcommands: &[],
};
