//! `squad` — the task daemon and everything that talks to it.
//!
//! Split out of `dispatch/catalogue.rs` by WI 0114 F-51. The specs are data;
//! `ROOT` in `mod.rs` is what assembles them into the tree.

use super::*;

// ── squad ────────────────────────────────────────────────────────────────────

pub(super) const SQUAD: CommandSpec = CommandSpec {
    name: "squad",
    aliases: &[],
    help: "Manage the squad task daemon and scheduled tasks.",
    long_help: None,
    arguments: &[],
    flags: &[
        FlagSpec {
            long: "non-interactive",
            short: Some('n'),
            help: "Print the squad status summary instead of opening the TUI.",
            kind: FlagKind::Bool,
            default: FlagDefault::Bool(false),
            frontends: FrontendVisibility::CliAndTui,
            conflicts_with: &[],
            implies: &[],
            optional: true,
        },
        FlagSpec {
            long: "json",
            short: None,
            help: "Emit JSON output.",
            kind: FlagKind::Bool,
            default: FlagDefault::Bool(false),
            frontends: FrontendVisibility::All,
            conflicts_with: &[],
            implies: &["non-interactive"],
            optional: true,
        },
    ],
    api_allowed: false,
    build: crate::command::dispatch::build::squad,
    gateway_need: GatewayNeed::IfRunning,
    requires_container_tier: true,
    requires_runtime: true,
    // `awman squad` on a terminal opens the squad tab; every subcommand below
    // is a one-shot.
    opens_tui_when_bare: true,
    subcommands: &[
        &SQUAD_START,
        &SQUAD_STOP,
        &SQUAD_STATUS,
        &SQUAD_LOGS,
        &SQUAD_ADD,
        &SQUAD_EDIT,
        &SQUAD_LIST,
        &SQUAD_SHOW,
        &SQUAD_REMOVE,
        &SQUAD_PAUSE,
        &SQUAD_RESUME,
        &SQUAD_TRIGGER,
        &SQUAD_CANCEL,
        &SQUAD_ATTACH,
        &SQUAD_ENV,
    ],
};

pub(super) const SQUAD_START: CommandSpec = CommandSpec {
    name: "start",
    aliases: &[],
    help: "Start the squad daemon.",
    long_help: None,
    arguments: &[],
    flags: &[
        FlagSpec {
            long: "port",
            short: None,
            help: "Port to listen on (0 selects an OS-assigned port).",
            kind: FlagKind::U16,
            default: FlagDefault::U16(0),
            frontends: FrontendVisibility::All,
            conflicts_with: &[],
            implies: &[],
            optional: true,
        },
        FlagSpec {
            long: "background",
            short: None,
            help: "Daemonize via the OS process manager.",
            kind: FlagKind::Bool,
            default: FlagDefault::Bool(false),
            frontends: FrontendVisibility::All,
            conflicts_with: &[],
            implies: &[],
            optional: true,
        },
        FlagSpec {
            long: "refresh-key",
            short: None,
            help: "Regenerate the squad key and print its AWMAN_SQUAD_KEY export snippet.",
            kind: FlagKind::Bool,
            default: FlagDefault::Bool(false),
            frontends: FrontendVisibility::All,
            conflicts_with: &[],
            implies: &[],
            optional: true,
        },
        FlagSpec {
            long: "dangerously-skip-auth",
            short: None,
            help: "Skip key creation and authentication for this run (loopback-only).",
            kind: FlagKind::Bool,
            default: FlagDefault::Bool(false),
            frontends: FrontendVisibility::All,
            conflicts_with: &[],
            implies: &[],
            optional: true,
        },
    ],
    api_allowed: true,
    build: crate::command::dispatch::build::squad,
    gateway_need: GatewayNeed::None,
    requires_container_tier: true,
    requires_runtime: true,
    opens_tui_when_bare: false,
    subcommands: &[],
};

pub(super) const SQUAD_STOP: CommandSpec = CommandSpec {
    name: "stop",
    aliases: &["kill"],
    help: "Stop the squad daemon.",
    long_help: None,
    arguments: &[],
    flags: &[],
    api_allowed: true,
    build: crate::command::dispatch::build::squad,
    gateway_need: GatewayNeed::None,
    requires_container_tier: true,
    requires_runtime: true,
    opens_tui_when_bare: false,
    subcommands: &[],
};

pub(super) const SQUAD_STATUS: CommandSpec = CommandSpec {
    name: "status",
    aliases: &[],
    help: "Show squad daemon status.",
    long_help: None,
    arguments: &[],
    flags: &[FlagSpec {
        long: "json",
        short: None,
        help: "Emit JSON output.",
        kind: FlagKind::Bool,
        default: FlagDefault::Bool(false),
        frontends: FrontendVisibility::All,
        conflicts_with: &[],
        implies: &[],
        optional: true,
    }],
    api_allowed: true,
    build: crate::command::dispatch::build::squad,
    gateway_need: GatewayNeed::IfRunning,
    requires_container_tier: true,
    requires_runtime: true,
    opens_tui_when_bare: false,
    subcommands: &[],
};

pub(super) const SQUAD_LOGS: CommandSpec = CommandSpec {
    name: "logs",
    aliases: &[],
    help: "Show the squad daemon log.",
    long_help: None,
    arguments: &[],
    flags: &[FlagSpec {
        long: "follow",
        short: Some('f'),
        help: "Follow the log as it grows.",
        kind: FlagKind::Bool,
        default: FlagDefault::Bool(false),
        frontends: FrontendVisibility::All,
        conflicts_with: &[],
        implies: &[],
        optional: true,
    }],
    api_allowed: true,
    build: crate::command::dispatch::build::squad,
    gateway_need: GatewayNeed::None,
    requires_container_tier: true,
    requires_runtime: true,
    opens_tui_when_bare: false,
    subcommands: &[],
};

/// The task-scoped agent pool, shared verbatim by `squad add` and
/// `squad edit` so both write the same `config.json` block (WI 0110).
pub(super) const SQUAD_AGENT_MODELS_FLAG: FlagSpec = FlagSpec {
    long: "agent-models",
    short: None,
    help: "Agents and models this task may use: <agent>=<model>[,<model>...]. Repeatable.",
    kind: FlagKind::VecString,
    default: FlagDefault::EmptyVec,
    frontends: FrontendVisibility::All,
    conflicts_with: &[],
    implies: &[],
    optional: true,
};

pub(super) const SQUAD_ADD: CommandSpec = CommandSpec {
    name: "add",
    aliases: &[],
    help: "Create a squad task.",
    long_help: None,
    arguments: &[],
    flags: &[
        FlagSpec {
            long: "name",
            short: None,
            help: "Task slug.",
            kind: FlagKind::String,
            default: FlagDefault::None,
            frontends: FrontendVisibility::All,
            conflicts_with: &[],
            implies: &[],
            optional: false,
        },
        FlagSpec {
            long: "description",
            short: None,
            help: "Task description.",
            kind: FlagKind::String,
            default: FlagDefault::None,
            frontends: FrontendVisibility::All,
            conflicts_with: &[],
            implies: &[],
            optional: false,
        },
        FlagSpec {
            long: "repo",
            short: None,
            help: "Legacy synonym for `--workspace <path>`; ignored when `--workspace` is given.",
            kind: FlagKind::Path,
            default: FlagDefault::None,
            frontends: FrontendVisibility::All,
            conflicts_with: &[],
            implies: &[],
            optional: true,
        },
        FlagSpec {
            long: "interval",
            short: None,
            help: "Evaluation interval (for example 6h).",
            kind: FlagKind::String,
            default: FlagDefault::Str("6h"),
            frontends: FrontendVisibility::All,
            conflicts_with: &[],
            implies: &[],
            optional: true,
        },
        FlagSpec {
            long: "agent",
            short: None,
            help: "Task-specific leader agent.",
            kind: FlagKind::String,
            default: FlagDefault::None,
            frontends: FrontendVisibility::All,
            conflicts_with: &[],
            implies: &[],
            optional: true,
        },
        FlagSpec {
            long: "model",
            short: None,
            help: "Task-specific leader model.",
            kind: FlagKind::String,
            default: FlagDefault::None,
            frontends: FrontendVisibility::All,
            conflicts_with: &[],
            implies: &[],
            optional: true,
        },
        FlagSpec {
            long: "workspace",
            short: None,
            help: "Task workspace: `default` for the durable per-task workspace, or a folder/repo path. Defaults to `default`.",
            kind: FlagKind::String,
            // Deliberately no catalogue default: Dispatch must be able to tell
            // "not given" from "given as default", because an absent
            // `--workspace` falls back to the legacy `--repo` before settling
            // on the durable workspace.
            default: FlagDefault::None,
            frontends: FrontendVisibility::All,
            conflicts_with: &[],
            implies: &[],
            optional: true,
        },
        FlagSpec {
            long: "overlay",
            short: None,
            help: "Overlay the task's containers get: dir()/ssh()/env()/skill(). Repeatable.",
            kind: FlagKind::VecString,
            default: FlagDefault::EmptyVec,
            frontends: FrontendVisibility::All,
            conflicts_with: &[],
            implies: &[],
            optional: true,
        },
        FlagSpec {
            long: "mount-scope",
            short: None,
            help: "Repository scope mounted for scheduled runs (custom git-repo workspaces only).",
            kind: FlagKind::Enum(&["cwd", "gitroot"]),
            default: FlagDefault::Str("gitroot"),
            frontends: FrontendVisibility::All,
            conflicts_with: &[],
            implies: &[],
            optional: true,
        },
        SQUAD_AGENT_MODELS_FLAG,
        FlagSpec {
            long: "interview",
            short: None,
            help: "Collect task fields interactively.",
            kind: FlagKind::Bool,
            default: FlagDefault::Bool(false),
            frontends: FrontendVisibility::CliAndTui,
            conflicts_with: &["non-interactive"],
            implies: &[],
            optional: true,
        },
        FlagSpec {
            long: "non-interactive",
            short: Some('n'),
            help: "Never prompt: refuse anything needing a confirmation instead of asking.",
            kind: FlagKind::Bool,
            default: FlagDefault::Bool(false),
            frontends: FrontendVisibility::CliAndTui,
            conflicts_with: &["interview"],
            implies: &[],
            optional: true,
        },
    ],
    api_allowed: true,
     build: crate::command::dispatch::build::squad,
    gateway_need: GatewayNeed::Running,
    requires_container_tier: true,
    requires_runtime: true,
    opens_tui_when_bare: false,
    subcommands: &[],
};

pub(super) const SQUAD_LIST: CommandSpec = CommandSpec {
    name: "list",
    aliases: &[],
    help: "List squad tasks.",
    long_help: None,
    arguments: &[],
    flags: &[FlagSpec {
        long: "json",
        short: None,
        help: "Emit JSON output.",
        kind: FlagKind::Bool,
        default: FlagDefault::Bool(false),
        frontends: FrontendVisibility::All,
        conflicts_with: &[],
        implies: &[],
        optional: true,
    }],
    api_allowed: true,
    build: crate::command::dispatch::build::squad,
    gateway_need: GatewayNeed::Running,
    requires_container_tier: true,
    requires_runtime: true,
    opens_tui_when_bare: false,
    subcommands: &[],
};

pub(super) const SQUAD_NAME_ARGUMENT: ArgumentSpec = ArgumentSpec {
    name: "name",
    help: "Task name.",
    kind: ArgumentKind::String,
    optional: false,
};

pub(super) const SQUAD_SHOW: CommandSpec = CommandSpec {
    name: "show",
    aliases: &[],
    help: "Show a squad task.",
    long_help: None,
    arguments: &[SQUAD_NAME_ARGUMENT],
    flags: &[FlagSpec {
        long: "json",
        short: None,
        help: "Emit JSON output.",
        kind: FlagKind::Bool,
        default: FlagDefault::Bool(false),
        frontends: FrontendVisibility::All,
        conflicts_with: &[],
        implies: &[],
        optional: true,
    }],
    api_allowed: true,
    build: crate::command::dispatch::build::squad,
    gateway_need: GatewayNeed::Running,
    requires_container_tier: true,
    requires_runtime: true,
    opens_tui_when_bare: false,
    subcommands: &[],
};
/// `squad edit` carries every field a task may change after creation. `name`,
/// `workspace` and `mount-scope` are absent on purpose: they are captured once
/// at creation and define the task's identity and isolation (WI 0110).
pub(super) const SQUAD_EDIT: CommandSpec = CommandSpec {
    name: "edit",
    aliases: &[],
    help: "Edit an existing squad task.",
    long_help: Some(
        "Change a task's description, schedule, leader agent/model, overlays, or agent pool. \
         A task's name, workspace and mount scope are fixed at creation and cannot be edited; \
         changing those means creating a new task. Every flag is optional, but at least one \
         must be given unless --interview is used.",
    ),
    arguments: &[SQUAD_NAME_ARGUMENT],
    flags: &[
        FlagSpec {
            long: "description",
            short: None,
            help: "Replace the task description.",
            kind: FlagKind::String,
            default: FlagDefault::None,
            frontends: FrontendVisibility::All,
            conflicts_with: &[],
            implies: &[],
            optional: true,
        },
        FlagSpec {
            long: "interval",
            short: None,
            help: "Replace the evaluation interval (for example 6h).",
            kind: FlagKind::String,
            default: FlagDefault::None,
            frontends: FrontendVisibility::All,
            conflicts_with: &[],
            implies: &[],
            optional: true,
        },
        FlagSpec {
            long: "agent",
            short: None,
            help: "Replace the task-specific leader agent.",
            kind: FlagKind::String,
            default: FlagDefault::None,
            frontends: FrontendVisibility::All,
            conflicts_with: &["clear-agent"],
            implies: &[],
            optional: true,
        },
        FlagSpec {
            long: "clear-agent",
            short: None,
            help: "Drop the task's own leader agent, falling back to the squad default.",
            kind: FlagKind::Bool,
            default: FlagDefault::Bool(false),
            frontends: FrontendVisibility::All,
            conflicts_with: &["agent"],
            implies: &[],
            optional: true,
        },
        FlagSpec {
            long: "model",
            short: None,
            help: "Replace the task-specific leader model.",
            kind: FlagKind::String,
            default: FlagDefault::None,
            frontends: FrontendVisibility::All,
            conflicts_with: &["clear-model"],
            implies: &[],
            optional: true,
        },
        FlagSpec {
            long: "clear-model",
            short: None,
            help: "Drop the task's own leader model, falling back to the squad default.",
            kind: FlagKind::Bool,
            default: FlagDefault::Bool(false),
            frontends: FrontendVisibility::All,
            conflicts_with: &["model"],
            implies: &[],
            optional: true,
        },
        FlagSpec {
            long: "overlay",
            short: None,
            help: "Replace the task's overlays: dir()/ssh()/env()/skill(). Repeatable.",
            kind: FlagKind::VecString,
            default: FlagDefault::EmptyVec,
            frontends: FrontendVisibility::All,
            conflicts_with: &["clear-overlays"],
            implies: &[],
            optional: true,
        },
        FlagSpec {
            long: "clear-overlays",
            short: None,
            help: "Remove every overlay from the task.",
            kind: FlagKind::Bool,
            default: FlagDefault::Bool(false),
            frontends: FrontendVisibility::All,
            conflicts_with: &["overlay"],
            implies: &[],
            optional: true,
        },
        SQUAD_AGENT_MODELS_FLAG,
        FlagSpec {
            long: "clear-agent-models",
            short: None,
            help: "Remove the task's own agent pool, inheriting the global squad settings.",
            kind: FlagKind::Bool,
            default: FlagDefault::Bool(false),
            frontends: FrontendVisibility::All,
            conflicts_with: &["agent-models"],
            implies: &[],
            optional: true,
        },
        FlagSpec {
            long: "interview",
            short: None,
            help: "Collect the edited fields interactively, prefilled with the current values.",
            kind: FlagKind::Bool,
            default: FlagDefault::Bool(false),
            frontends: FrontendVisibility::CliAndTui,
            conflicts_with: &["non-interactive"],
            implies: &[],
            optional: true,
        },
        FlagSpec {
            long: "non-interactive",
            short: Some('n'),
            help: "Never prompt: refuse anything needing a confirmation instead of asking.",
            kind: FlagKind::Bool,
            default: FlagDefault::Bool(false),
            frontends: FrontendVisibility::CliAndTui,
            conflicts_with: &["interview"],
            implies: &[],
            optional: true,
        },
    ],
    api_allowed: true,
    build: crate::command::dispatch::build::squad,
    gateway_need: GatewayNeed::Running,
    requires_container_tier: true,
    requires_runtime: true,
    opens_tui_when_bare: false,
    subcommands: &[],
};

pub(super) const SQUAD_REMOVE: CommandSpec = CommandSpec {
    name: "remove",
    aliases: &[],
    help: "Remove a squad task.",
    long_help: None,
    arguments: &[SQUAD_NAME_ARGUMENT],
    flags: &[FlagSpec {
        long: "yes",
        short: Some('y'),
        help: "Do not prompt for confirmation.",
        kind: FlagKind::Bool,
        default: FlagDefault::Bool(false),
        frontends: FrontendVisibility::CliAndTui,
        conflicts_with: &[],
        implies: &[],
        optional: true,
    }],
    api_allowed: true,
    build: crate::command::dispatch::build::squad,
    gateway_need: GatewayNeed::Running,
    requires_container_tier: true,
    requires_runtime: true,
    opens_tui_when_bare: false,
    subcommands: &[],
};
pub(super) const SQUAD_PAUSE: CommandSpec = CommandSpec {
    name: "pause",
    aliases: &[],
    help: "Pause a squad task.",
    long_help: None,
    arguments: &[SQUAD_NAME_ARGUMENT],
    flags: &[],
    api_allowed: true,
    build: crate::command::dispatch::build::squad,
    gateway_need: GatewayNeed::Running,
    requires_container_tier: true,
    requires_runtime: true,
    opens_tui_when_bare: false,
    subcommands: &[],
};
pub(super) const SQUAD_RESUME: CommandSpec = CommandSpec {
    name: "resume",
    aliases: &[],
    help: "Resume a squad task.",
    long_help: None,
    arguments: &[SQUAD_NAME_ARGUMENT],
    flags: &[],
    api_allowed: true,
    build: crate::command::dispatch::build::squad,
    gateway_need: GatewayNeed::Running,
    requires_container_tier: true,
    requires_runtime: true,
    opens_tui_when_bare: false,
    subcommands: &[],
};
pub(super) const SQUAD_TRIGGER: CommandSpec = CommandSpec {
    name: "trigger",
    aliases: &[],
    help: "Evaluate a squad task now, ignoring its schedule.",
    long_help: Some(
        "Ask the squad daemon to evaluate a task on its next scheduler tick, whatever \
         its interval says and whatever backoff is outstanding. The task's interval is \
         not changed: the trigger fires exactly one evaluation, after which the task \
         returns to its normal schedule. A paused task is refused — resume it first.",
    ),
    arguments: &[SQUAD_NAME_ARGUMENT],
    flags: &[],
    api_allowed: true,
    build: crate::command::dispatch::build::squad,
    gateway_need: GatewayNeed::Running,
    requires_container_tier: true,
    requires_runtime: true,
    opens_tui_when_bare: false,
    subcommands: &[],
};
pub(super) const SQUAD_CANCEL: CommandSpec = CommandSpec {
    name: "cancel",
    aliases: &[],
    help: "Cancel a squad task's in-progress run.",
    long_help: Some(
        "Stop the run a squad task is executing right now: its evaluation is abandoned, \
         every agent container it started is stopped, and the run is recorded as \
         canceled in the task's history. The task keeps its schedule and is evaluated \
         again when next due. Fails when the task has no run in progress.",
    ),
    arguments: &[SQUAD_NAME_ARGUMENT],
    flags: &[],
    api_allowed: true,
    build: crate::command::dispatch::build::squad,
    gateway_need: GatewayNeed::Running,
    requires_container_tier: true,
    requires_runtime: true,
    opens_tui_when_bare: false,
    subcommands: &[],
};
pub(super) const SQUAD_ATTACH: CommandSpec = CommandSpec {
    name: "attach",
    aliases: &[],
    help: "Attach to a running squad task container.",
    long_help: None,
    arguments: &[SQUAD_NAME_ARGUMENT],
    flags: &[FlagSpec {
        long: "container",
        short: None,
        help: "Running container ID when multiple are active.",
        kind: FlagKind::String,
        default: FlagDefault::None,
        frontends: FrontendVisibility::CliAndTui,
        conflicts_with: &[],
        implies: &[],
        optional: true,
    }],
    api_allowed: false,
    build: crate::command::dispatch::build::squad_attach,
    gateway_need: GatewayNeed::Running,
    requires_container_tier: true,
    requires_runtime: true,
    opens_tui_when_bare: false,
    subcommands: &[],
};

/// `squad env` — the one home for the daemon's env coverage (WI 0116 §6d).
///
/// `api_allowed: false` is deliberate and is a security property, not an
/// oversight: an API-allowed leaf can be driven through the `/v1/commands`
/// `{subcommand, args}` envelope, where CLI-arg-shaped strings drift into
/// tracing spans and error text. Payload values must never travel that way, so
/// the whole leaf stays off the API front door. The daemon's own typed
/// `/v1/daemon/env` route is the only way env data crosses the socket.
pub(super) const SQUAD_ENV: CommandSpec = CommandSpec {
    name: "env",
    aliases: &[],
    help: "Show which env() values the squad daemon has, and where they came from.",
    long_help: Some(
        "Report every environment variable the squad daemon needs — the union of every \
         env(NAME) overlay across the task store, the daemon's own config and \
         AWMAN_OVERLAYS — with whether the daemon currently holds a value, where that \
         value came from (this shell, a previous push, or the OS keychain at startup), \
         and how long any missing one has been missing.\n\n\
         Values are never printed: this command reports only whether one is present. \
         Running it with no flag also performs the ordinary coverage check, which sends \
         a value only when it actually differs from what the daemon holds. --push \
         re-sends every value this shell has regardless, which is what to reach for \
         after rotating a token. --clear removes the daemon's persisted keychain item; \
         the running daemon keeps the values it already holds.",
    ),
    arguments: &[],
    flags: &[
        FlagSpec {
            long: "push",
            short: None,
            help: "Push every required value this shell has, whether or not it differs.",
            kind: FlagKind::Bool,
            default: FlagDefault::Bool(false),
            frontends: FrontendVisibility::All,
            conflicts_with: &[],
            implies: &[],
            optional: true,
        },
        FlagSpec {
            long: "clear",
            short: None,
            help: "Remove the daemon's persisted keychain item.",
            kind: FlagKind::Bool,
            default: FlagDefault::Bool(false),
            frontends: FrontendVisibility::All,
            conflicts_with: &[],
            implies: &[],
            optional: true,
        },
        FlagSpec {
            long: "json",
            short: None,
            help: "Emit JSON output.",
            kind: FlagKind::Bool,
            default: FlagDefault::Bool(false),
            frontends: FrontendVisibility::All,
            conflicts_with: &[],
            implies: &[],
            optional: true,
        },
    ],
    api_allowed: false,
    build: crate::command::dispatch::build::squad,
    gateway_need: GatewayNeed::Running,
    requires_container_tier: true,
    requires_runtime: true,
    opens_tui_when_bare: false,
    subcommands: &[],
};
