use strict; use warnings;
sub edit { my($file,$from,$to)=@_; local $/; open my $in,'<',$file or die $!; my $s=<$in>; close$in; index($s,$from)>=0 or die "not found: $file $from"; $s =~ s/\Q$from\E/$to/g; open my $out,'>',$file or die$!; print $out $s; }
edit('docs/11-runtimes.md', 'Every session VM gets its own network stack running in the host-side worker process. The preview still refuses some allowed HTTPS connections. Hostname allow rules are limited to TCP; UDP/QUIC is denied because the stack cannot enforce its hostname boundary for those protocols. Native enforcement remains unverified.', 'Every session VM gets its own network stack running in the host-side worker process. Allowed HTTPS passes host-side stack tests with end-to-end TLS. Hostname allow rules are limited to TCP; UDP/QUIC is denied because the stack cannot inspect its hostname boundary for those protocols. Enforcement inside real guests remains unverified.');
edit('docs/11-runtimes.md', '**DNS** is configured for interception by the host-side stack. The intended allowlist contract requires both allowed DNS names and allowed connection authorities; allowed HTTPS is still blocked by the current SDK integration. A DNS answer does not grant a hostname rule permission to use UDP/QUIC. Upstream resolvers default to the host\'s own resolver configuration, or set `nameservers` (global only; IP or `IP:PORT`, never a host name, so resolving a resolver never depends on one).', '**DNS and HTTPS.** The host-side stack intercepts DNS. For HTTPS authorized by a hostname rule, the visible TLS ClientHello server name (SNI) must be allowed and that exact name must have a DNS binding to the destination IP. An allowed sibling name or a shared IP alone does not authorize the connection. Missing or unlisted visible SNI is refused. The connection remains encrypted end to end: awman cannot inspect encrypted HTTP `Host`/`:authority`, domain fronting behind an allowed server, or the hidden inner name of Encrypted ClientHello (ECH). An allowed ECH outer name proves only that outer name. Use services you trust within this boundary; it is not a guarantee about every logical destination carried inside an allowed encrypted connection. A DNS answer does not authorize UDP/QUIC. Upstream resolvers default to the host\'s own resolver configuration, or set `nameservers` (global only; IP or `IP:PORT`, never a host name, so resolving a resolver never depends on one). Native guest tests remain required.');
edit('docs/11-runtimes.md', 'Allowed HTTPS still has a refusal defect; hostname rules deny UDP/QUIC; native enforcement remains unverified', 'HTTPS checks visible SNI plus its exact DNS/IP binding; encrypted HTTP authority and ECH inner names are not inspected. Hostname rules deny UDP/QUIC; native enforcement remains unverified');
edit('aspec/architecture/security.md', '- **Builtin guest network policy (required contract; not verified)** — Policy enforcement belongs in the SDK host-side worker stack. Guest traffic must obey the configured destinations, DNS, host-port and resource boundaries without TLS interception, ambient proxy inheritance or a host helper. Repo settings may only narrow the global ceiling. Current allowlist integration still FAILS this contract: strict opaque HTTPS rejects allowed authorities. Name-based allow rules now admit TCP only, preventing cached DNS from authorizing UDP/QUIC to an unlisted co-host. Configuration/serialization tests do not prove enforcement; native denied-egress and positive-control tests remain required. The HTTPS defect is not a parity exception. See the [WI 0121 evidence register](../review-notes/0121-evidence-register.md).', '- **Builtin guest network policy (native enforcement unverified)** — Policy enforcement belongs in the SDK host-side worker stack. Guest traffic must obey configured destinations, DNS, host-port and resource boundaries without TLS interception, ambient proxy inheritance or a host helper. Repo settings may only narrow the global ceiling. The explicit `strict_sni` mode keeps strict checking enabled and admits end-to-end TLS only when visible ClientHello SNI matches an allowed name and that exact name has a DNS binding to the destination IP. Missing/unlisted SNI, missing bindings and sibling-name bindings cannot authorize a name-based TLS flow. Host-side SDK tests exercise a real TLS handshake and denied requests before upstream connection. This boundary does not inspect encrypted HTTP `Host`/`:authority`, domain fronting behind an allowed service, or ECH inner names; an allowed outer SNI establishes only that outer name. Name rules admit TCP only, preventing cached DNS from authorizing UDP/QUIC. Native guest denied-egress, positive-control and isolation tests remain required; host-side tests do not prove guest packet routing. See the [WI 0121 evidence register](../review-notes/0121-evidence-register.md).');
edit('third_party/README.md', '| `microsandbox-0.7.2` | Isolated local backend builder that ignores installed Microsandbox config | Pinned upstream isolated builder plus hostile-config and native coexistence checks |', '| `microsandbox-0.7.2` | Isolated local backend builder that ignores installed Microsandbox config | Pinned upstream isolated builder plus hostile-config and native coexistence checks |
| `microsandbox-network-0.7.2` | Explicit visible-SNI enforcement without interception; exact DNS binding for suffix rules | Equivalent pinned upstream option plus SDK-boundary and native guest network tests |
| `microsandbox-types-0.7.2` | Preserve `strict_sni` through local/cloud NetworkSpec conversions | Remove with network patch after configuration roundtrip and native tests |');
edit('third_party/README.md', 'Microsandbox source baseline is', 'The six carried crate patches include the paired network/types changes. Their published archive hashes are `be4f1c9d36c1957b35d674a993a59c5db1741f47c96c952b491b09d9674b92d7` and `8f705cfd6b163fc5b00987c6cf6143b5ceed311b097e68926822b2d6daa4cfee`; their patch hashes are `993d00b0d99e436e2cebc72a8a5ccbadcfb458b8ba1d9ad4cb242bafdcc2e100` and `30bf86e5a7e58acbe889d3d05eb898795b3078dedc608d0435b252196c6eed4f`, respectively. Both are Apache-2.0. See [network provenance and boundary](microsandbox-network-0.7.2/PATCH.md) and [types provenance](microsandbox-types-0.7.2/PATCH.md).

Microsandbox source baseline is');
edit('NOTICE.third-party.md', '`msb_krun` and `microsandbox-filesystem` are Apache-2.0 licensed; their vendored license files are in each directory.', '`msb_krun`, `microsandbox-filesystem`, `microsandbox`, `microsandbox-network`, and `microsandbox-types` are Apache-2.0 licensed; their vendored license files are in each directory. Together with `sqlx-sqlite`, these are the six carried crate patches listed in [third_party/README.md](third_party/README.md). The network/types 0.7.2 sources share Microsandbox revision `60d4dc8a436fb9365491567ec21d073e924e3c6d`; their [network](third_party/microsandbox-network-0.7.2/PATCH.md) and [types](third_party/microsandbox-types-0.7.2/PATCH.md) patch notes record exact archive/diff hashes, reconstruction and removal gates.');
my $wi='aspec/work-items/0120-upstream-embedded-kernel-support.md';
edit($wi, 'WI 0119 carries three patched published crates; WI 0121 adds the patched
Microsandbox SDK crate.', 'WI 0119 carries three patched published crates; WI 0121 adds the patched
Microsandbox SDK, network and types crates, for six carried dependency patches.');
edit($wi, 'and integration changes, not additional vendored patches; the four-patch
inventory above remains unchanged.', 'and integration changes. The paired network/types patches below separately
raise the carried dependency inventory to six.');
edit($wi, 'patch at `third_party/microsandbox-0.7.2/PATCH.md`. No patch acceptance or', 'patch at `third_party/microsandbox-0.7.2/PATCH.md` and paired network/types
patches at `third_party/microsandbox-network-0.7.2/PATCH.md` and
`third_party/microsandbox-types-0.7.2/PATCH.md`. No patch acceptance or');
