use strict; use warnings;
my $p='aspec/review-notes/0121-evidence-register.md';
open my $f,'<',$p or die $!; local $/; my $s=<$f>; close $f;
$s =~ s/source\.sha256\]\(0121-evidence\/raw\/completion\/source\.sha256\)/source.sha256](0121-evidence\/raw\/closure\/source.sha256)/;
my %rows=(
'D-02' => '| D-02 | `oci/{docker_engine,registry,retry,transport,sources}.rs`; `tests/oci_import/{cancellation,real_stores}.rs`; production Ready import | Caller/drop/Ctrl-C cancellation now reaches acquisition, projection and import locks; HTTP futures close peer sockets during header/body/token waits. [Acquisition notes](0121-evidence/raw/closure/acquisition/notes.md), [OCI execution](0121-evidence/raw/closure/focused-oci.log). Real Unix/TLS/mTLS and required auth/private-CA/observed-proxy scenarios exist, but did not execute. Real expiry/disconnect/retry and source-stop cached guest scenarios still need completion in WI 0123. **FAIL** for incomplete mandatory scenarios; real-service execution **BLOCKED**. SDK mutation finishes coherently before cancellation is reported; no immediate-abort claim. |',
'D-04' => '| D-04 | `tests/builtin_runtime/guest_compat.rs`, `builtin/backend/matrix_tests.rs` | Registered actual-awman non-root nine-agent × named/all-skills scenario covers shipped settings/prompt families, HOME, overlays and writeback. [Matrix notes](0121-evidence/raw/closure/matrix/notes.md). Its native run fails prerequisites: zero guest executions. Artificial descriptor strategy combinations, live atomic refresh with multiple consumers and complete defaults/overrides still need WI 0123 implementation. **FAIL**, native execution **BLOCKED**. No strategy exempted. |',
'D-05' => '| D-05 | `builtin/{network,msb_driver,resources}.rs`; patched network/types SDK; `tests/builtin_runtime/network_resources.rs` | Explicit strict SNI now passes actual proxy TLS handshake/application data; wrong/missing/unbound/sibling SNI is refused before dial. Exact DNS-name/IP binding and TCP-only name rules retain UDP/QUIC denial. [Executed network tests and limits](0121-evidence/raw/closure/network/notes.md). Controlled endpoint probe classification is fixed. Full guest auth/DNS/MCP/proxy/CA/network/OOM/CPU scenarios still need WI 0123 completion and execution. **FAIL** for remaining scenario code; native enforcement **BLOCKED**. Encrypted HTTP authority/ECH inner-name inspection is not claimed. |',
'D-09' => '| D-09 | `oci/{mod,cache}.rs`, `builtin/{paths,backend,instance}.rs`, attach/exec bridge | Atomic archive leases survive cloned handoff and cross-process prune. New shared image leases protect launch plans; exclusive import/remove refuses competing use, then SDK rootfs references protect the installed image. Cross-process lock and planned-image removal regressions execute in [focused local log](0121-evidence/raw/closure/focused-local.log). Broader native multi-process crash/stress scenarios remain incomplete in WI 0123. **FAIL**, native execution **BLOCKED**. |',
'D-12' => '| D-12 | `tests/builtin_runtime/sqlite.rs`, SQLx 0.9.0/rusqlite 0.40.2 and bundled libsqlite3-sys 0.38.2 | Exact resolution/migration/debug DSO checks plus genuine SQLx/rusqlite bidirectional commit, rollback, uncommitted visibility and SQLITE_BUSY contention execute against one SDK catalog on Linux ARM64. Actual awman reopens it with 27 migrations. [Executed SQLite test](0121-evidence/raw/closure/sqlite-transactions.log), [hermetic suite](0121-evidence/raw/closure/hermetic-builtin.log). Historical full-spike artifacts remain absent; genuine old/new builds and every supported native target remain **BLOCKED**, assigned WI 0123. No database-contract or SQLite DSO exception. |',
'D-15' => '| D-15 | `tests/oci_import/corpus.rs`, corpus builder, guest/onboarding scenarios | Full required format × shipped-template corpus builder/consumer now exists with production size limits; shell syntax and synthetic formats execute. [Matrix notes](0121-evidence/raw/closure/matrix/notes.md). Actual corpus production is **BLOCKED** without Docker/Apple services. Complete onboarding and remaining guest strategy scenarios need WI 0123 implementation: **FAIL**. No parity exemption created. |',
);
for my $id(keys %rows) { $s =~ s/^\| \Q$id\E \|.*$/$rows{$id}/m or die "missing $id"; }
$s =~ s/Four patched vendor crates/Six patched vendor crates/;
$s =~ s/D-04\/D-05\/D-06\/D-09: missing matrix and enforcement\/cache defects/D-04\/D-05\/D-06\/D-09: remaining native strategy, network and lifecycle scenarios/;
$s =~ s/## Final adversarial verification\n/## Final adversarial verification — earlier completion snapshot\n/;
$s =~ s/\*\*Audit date: 2026-09-28\. Overall: NOT ACCEPTED\.\*\*/**Audit date: 2026-09-28. Overall runtime acceptance: NOT ACCEPTED.**/;
my $handoff="\nThe latest user instruction authorizes resource-qualified follow-ups: [WI 0122](../work-items/0122-native-apple-image-store-bridge.md) owns the missing Apple-store implementation; [WI 0123](../work-items/0123-builtin-native-verification-and-release-closure.md) owns remaining native scenarios, full-diff/clean-build verification, services and release closure. These are open assignments awaiting capable runner access, not executed jobs. Their creation does not satisfy an original mandatory gate. The latest final verification section below supersedes earlier snapshot descriptions.\n";
$s =~ s/(never evidence of guest\/service\/distribution execution\.\n)/$1$handoff/;
open $f,'>',$p or die $!; print $f $s; close $f;
